runtime: python311

entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT api.main:app

instance_class: F4

env_variables:
  GCS_LOG_BUCKET: "ids-logs-george-thomas"
  IPINFO_TOKEN: "fc1cac7b1c3f2f"

  IDS_MAX_ROWS: "500"
  IDS_MAX_DETAILS: "100"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

handlers:
  - url: /.*
    script: auto
