runtime: python311

entrypoint: uvicorn api.main:app --host 0.0.0.0 --port $PORT

env_variables:
  GCS_LOG_BUCKET: "ids-logs-george-thomas"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
